networks:
  backend:

volumes:
  pgdata:
  appdata:
  redisdata:

services:
  db:
    image: postgres:16
    container_name: iss_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-monolith}
      POSTGRES_USER: ${POSTGRES_USER:-monouser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-monopass}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-monouser} -d ${POSTGRES_DB:-monolith}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - backend
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: iss_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redisdata:/data
    networks:
      - backend

  rust_iss:
    build:
      context: ./services/rust-iss
    container_name: rust_iss
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://monouser:monopass@db:5432/monolith}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      
      NASA_API_URL: ${NASA_API_URL:-}
      NASA_API_KEY: ${NASA_API_KEY:-}
      WHERE_ISS_URL: ${WHERE_ISS_URL:-https://api.wheretheiss.at/v1/satellites/25544}
      
      FETCH_EVERY_SECONDS: ${FETCH_EVERY_SECONDS:-600}
      ISS_EVERY_SECONDS: ${ISS_EVERY_SECONDS:-120}
      APOD_EVERY_SECONDS: ${APOD_EVERY_SECONDS:-43200}
      NEO_EVERY_SECONDS: ${NEO_EVERY_SECONDS:-7200}
      DONKI_EVERY_SECONDS: ${DONKI_EVERY_SECONDS:-3600}
      SPACEX_EVERY_SECONDS: ${SPACEX_EVERY_SECONDS:-3600}

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8081:3000"

  php:
    build:
      context: ./services/php-web
    container_name: php_web
    environment:
      JWST_HOST: ${JWST_HOST}
      JWST_API_KEY: ${JWST_API_KEY}
      JWST_EMAIL: ${JWST_EMAIL}
      JWST_PROGRAM_ID: ${JWST_PROGRAM_ID}
      ASTRO_APP_ID: ${ASTRO_APP_ID}
      ASTRO_APP_SECRET: ${ASTRO_APP_SECRET}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB:-monolith}
      DB_USERNAME: ${POSTGRES_USER:-monouser}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-monopass}
      
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RUST_BASE: ${RUST_BASE:-http://rust_iss:3000}

    depends_on:
      db:
        condition: service_healthy
      rust_iss:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - appdata:/var/www/html
      - ./services/php-web/laravel-patches:/opt/laravel-patches:ro

  nginx:
    image: nginx:1.27-alpine
    container_name: web_nginx
    depends_on:
      - php
    volumes:
      - appdata:/var/www/html:ro
      - ./services/php-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
    ports:
      - "8080:80"

  telemetry-legacy:
    build: ./services/telemetry-legacy
    container_name: telemetry_legacy
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      GEN_PERIOD_SEC: ${PAS_LEGACY_PERIOD:-300}
    networks:
      - backend